# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Pull request CI checks

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.{txt,md}"

# TODO: replace this with real jobs
jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: npm install

      - name: check with prettier
        run: npx prettier "**/*" --check

  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: npm install

      - name: check with eslint
        run: npx eslint "{src,test}/**/*" --max-warnings=0

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - name: install
        run: npm install

      - name: run testcases
        run: npm test
